name: matrix-job
on: push
jobs:
  test:
    continue-on-error: true
    strategy:
      matrix:
        os-type: ['ubuntu-latest','windows-latest']
        node-version: [12,13,14]
        include:
           - os-type: ubuntu-latest
             node-version: 14
        exclude: 
            - os-type: 'windows-latest'
              node-version: 12

    runs-on: ${{matrix.os-type}}
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: install node
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.node-version}}
        - name: install dependencies
          run: npm ci
        - name: run tests
          run: npm run test
        - name: build the code
          run: npm run build